import streamlit as st
import pandas as pd
import joblib

# Load trained model and feature names
model = joblib.load("student_grade_model.pkl")
feature_names = joblib.load("feature_names.pkl")

st.set_page_config(page_title="Student Grade Predictor", page_icon="🎓")

st.title("🎓 Student Academic Performance Predictor")

st.markdown("---")

st.markdown("""
### 📋 How to Use
Adjust the sliders below to match a student's profile and click **Predict Grade**.

The prediction is based on demographic, family, and lifestyle factors using a Random Forest machine learning model.
""")

st.markdown("---")
st.write(
    "Predict a student's final grade using a machine learning model trained on demographic, family, and lifestyle data."
)

# --------------------
# User Inputs
# --------------------

age = st.slider("Age", 15, 22, 17)

studytime = st.slider(
    "📚 Daily Study Time (1 = <2 hrs, 2 = 2–5 hrs, 3 = 5–10 hrs, 4 = >10 hrs)",
    1, 4, 2
)

traveltime = st.slider(
    "🚌 Travel Time (1 = <15 min, 2 = 15–30 min, 3 = 30–60 min, 4 = >60 min)",
    1, 4, 1
)

health = st.slider(
    "❤️ Health Rating (1 = Very Poor, 5 = Excellent)",
    1, 5, 3
)

famrel = st.slider(
    "👨‍👩‍👧 Family Relationship (1 = Very Bad, 5 = Excellent)",
    1, 5, 4
)

goout = st.slider(
    "🎉 Social Outings (1 = Very Rarely, 5 = Very Frequently)",
    1, 5, 3
)

freetime = st.slider(
    "⏰ Free Time After School (1 = Very Little, 5 = A Lot)",
    1, 5, 3
)

failures = st.slider(
    "❌ Previous Academic Failures",
    0, 4, 0
)

absences = st.slider(
    "🏫 Number of School Absences",
    0, 50, 5
)
# --------------------
# Create input dataframe
# --------------------

input_data = pd.DataFrame(0, index=[0], columns=feature_names)

# Fill numerical features
input_data["age"] = age
input_data["studytime"] = studytime
input_data["failures"] = failures
input_data["absences"] = absences
input_data["health"] = health
input_data["famrel"] = famrel
input_data["freetime"] = freetime
input_data["goout"] = goout
input_data["traveltime"] = traveltime

# --------------------
# Prediction
# --------------------

if st.button("Predict Grade"):

    prediction = model.predict(input_data)[0]

    # Display prediction
    st.success(f"🎯 Predicted Final Grade: {prediction:.1f} / 20")

    st.info("📘 Note: The dataset uses a grading scale from 0 to 20.")

    # Performance message
    if prediction < 10:
        st.error("⚠️ Predicted below the passing grade.")
    elif prediction < 15:
        st.info("📚 Predicted average academic performance.")
    else:
        st.success("🌟 Predicted strong academic performance!")

    # Personalized Suggestions
    st.subheader("💡 Personalized Suggestions")

    suggestions = []

    if studytime < 3:
        suggestions.append("📚 Increase your daily study time by 1–2 hours.")

    if absences > 10:
        suggestions.append("🏫 Try to reduce school absences to improve learning consistency.")

    if health < 3:
        suggestions.append("❤️ Improve your sleep, nutrition, and physical activity.")

    if famrel < 3:
        suggestions.append("👨‍👩‍👧 Seek support from family or trusted mentors when possible.")

    if goout > 4:
        suggestions.append("🎉 Consider reducing social outings during important academic periods.")

    if failures > 0:
        suggestions.append("📖 Spend extra time reviewing subjects you've previously struggled with.")

    if prediction >= 15:
        suggestions.append("🌟 Excellent! Keep maintaining your current study habits.")

    if len(suggestions) == 0:
        st.success("✅ No major improvement areas detected based on the selected inputs.")

    else:
        for suggestion in suggestions:
            st.write("•", suggestion)

    st.caption(
        "This prediction is generated by a machine learning model trained on the UCI Student Performance Dataset. "
        "It provides an estimate based on the selected inputs and should not be interpreted as a guarantee of future academic performance."
    )
